### ISSUE TITLE
How to run for a custom dataset

### ISSUE THREAD

**Issue by avinashsai** [DeepLearnXMU/NSEG#5]
Hi,
I have sentences in this order(example):
S1,S2,S3
S4,S1,S5

1.How can I convert the above sentence order to run this algorithm??
2.Can I use this algorithm to predict next sentence??
3.If I give a new sentence S6 how to predict next sentence??

**Comment by ARIES-LM** [comment]
Hi. 
I guess that you want to reorder a paragraph which has some identical sentences.  Since these two S1 have different indexes, i.e. 0 and 4 in this example, the algorithm does not need modificaiton in this case. On the other hand, S1 can also be regarded as one node. If so, the mask should be removed because a node can be pointed more than once.
This algorithem is based on the pointer machnism and is not generative. The input should be complete. I think it can't predict next sentence.
